### ISSUE TITLE
invalid characters in album name result in empty folders

### ISSUE THREAD

**Issue by serveral1** [Amenly/EroMe#3]
sometimes albums have characters in their names that aren't compatible with the system's file structure, so things like a closing bracket ")" or asterisks * and plus signs + end up causing conflicts, at least on windows.

here's an error message for when then erome script is run with the -s arg
`Traceback (most recent call last):
  File "c:\users\wep\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wep\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\WEP\AppData\Local\Programs\Python\Python38\Scripts\erome.exe\__main__.py", line 7, in <module>
  File "c:\users\wep\appdata\local\programs\python\python38\lib\site-packages\erome\erome.py", line 274, in main
    erome.handle_album(url)
  File "c:\users\wep\appdata\local\programs\python\python38\lib\site-packages\erome\erome.py", line 63, in handle_album
    os.makedirs(self.dir, exist_ok=True)
  File "c:\users\wep\appdata\local\programs\python\python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\WEP\\Workplace\\EroMe\\chloewarm (ig \\Videos'`
here's the album link for testing purposes https://www.erome.com/a/knKA19bL

**Comment by serveral1** [comment]
so i decided to dig around the code and found out that there are some preemptive measures set in place for those cases, and that the brackets in the album name weren't the ones causing the issue. however it seems that in this particular gallery (and some others that had similar naming schemes) there was a lone 32 bit space character (" ") at the end of the album title that was causing the issue. so i just added a space character to the character list at line 250 and, voila!, no more file system errors.

i'll leave the closing of the issue to the maintainer since my dirty fix might not be the best way of approaching the issue.

**Comment by Amenly** [comment]
Sorry for the late reply. This is very weird indeed, I didn't think a space at the end would cause an error. I think I'll add a strip() function to the album title to remove any spaces at the front and back. Also, I'm probably going to rewrite the script since it's getting harder to maintain and I'll be able to make it cleaner and more readable. Thanks for filing the issue though!
